
spring:
  cloud:
    stream:
      bindings:
        input-channel-1:
          destination: message
        output-channel-1:
          destination: validate2
      kafka:
        streams:
          binder:
            applicationId: transformstreams
            brokers: localhost:9092
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            output-channel-1:
              producer:
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
